# -*- coding: utf-8 -*-
"""app/viewer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oz546-c4YJeJbKfkQSltovva2L0NUn92
"""

# app/viewer.py
import matplotlib.pyplot as plt

def show_slice(dicom_files, slice_num=0):
    img = dicom_files[slice_num].pixel_array
    plt.imshow(img, cmap='gray')
    plt.title(f"Slice {slice_num + 1}")
    plt.axis('off')
    plt.show()